### ISSUE TITLE
What is meant by a proof a temporal proposition?

### ISSUE THREAD

**Issue by turion** [Aerate/FRP#7]
In the usual semantics, a temporal proposition is assumed to be true if it holds _now_, i.e. if `a : Atom` is an atom and `b : Nat -> Atoms -> Bool` is a valuation then `b` entails `a` iff `b 0 a`. The Oxford brackets have an implicit global modality, though: An inhabitant of `[[ r ]]` proves the temporal proposition `r` for all times. This is often what we want, but it's confusing for people who don't know the framework, so this should most probably be changed into proving only the head of an `RSet`.

**Comment by Aerate** [comment]
exchanged the brackets with different constructors & refined the global modality
